print("hello india",10,20.5)
print("hello world","hello india","hello python students")

# #=comment(ignored by compilers and interpreters)
# \n = to create newline

#variables
a=10
print(a)
b=20
print(b)
print(a+b)
print(a*b)

print('Hello World') #string
print(5) #integer
print(5.0) #float
print(True) #boolean
print(False) #boolean
print(None) #NoneType
#Variables
x = 5
print(x)
y = 10
print(y)
z = x + y
print(z)
#Data Types
#1 String
#2 Integer
#3 Float
#4 Boolean